name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install SSH Client
      if: github.event_name != 'pull_request' || github.repository == github.event.pull_request.head.repo.full_name # if NOT a PR or a PR that is NOT from a fork
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.FRANKLIN_PRIV }}
    - name: Fix URLs for PR preview deployment (pull request previews)
      if: github.event_name == 'pull_request'
      run: |
        echo "PREVIEW_FRANKLIN_WEBSITE_URL=https://preview.www-widmann-dev.pages.dev/PR${{ github.event.number }}/" >> $GITHUB_ENV
        echo "PREVIEW_FRANKLIN_PREPATH=PR${{ github.event.number }}" >> $GITHUB_ENV
    # NOTE: Python is necessary for pre-rendering steps.
    - name: Install python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1'
    # NOTE
    #   The steps below ensure that NodeJS and Franklin are loaded then it
    #   installs highlight.js which is needed for the prerendering step.
    #   Then the environment is activated and instantiated to install all
    #   Julia packages which may be required to successfully build your site.
    #
    #   The last line should be `optimize()` though you may want to give it
    #   specific arguments, see the documentation or ?optimize in the REPL.
    - name: Build site
      run: |
        using Pkg
        Pkg.instantiate()
        using NodeJS
        run(`$(npm_cmd()) install highlight.js`)
        using Franklin
        optimize()
      shell: julia --color=yes --project=. {0}
    - name: Deploy (preview)
      continue-on-error: true
      if: github.event_name == 'pull_request'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: preview
        FOLDER: __site
        TARGET_FOLDER: "PR${{ github.event.number }}"
    - name: Publish webpage (preview)
      if: github.event_name == 'pull_request'
      run: curl -s -X POST "https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/${{ secrets.SECRET_CLOUDFARE_DEPLOYKEY_PREVIEW }}" | jq -r -e ".success and isempty(.errors[])"
    - name: Deploy (main)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: site
        FOLDER: __site
    - name: Publish webpage (main)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: curl -s -X POST "https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/${{ secrets.SECRET_CLOUDFARE_DEPLOYKEY }}" | jq -r -e ".success and isempty(.errors[])"
